//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uyg02._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogrenci
    {
        public int ogrId { get; set; }
        public string ogrNo { get; set; }
        public string ogrAdsoyad { get; set; }
        public string ogrMail { get; set; }
        public int ogrYas { get; set; }
    }
}
